### PR TITLE
add an easy test

### PR DESCRIPTION
**Pull request by dougfort**

### CODE REVIEW

**Comment by justincely** [comment]
mhmm, somehow the total coverage went down

**Comment by dougfort** [comment]
Yes, I have seen this before. I think their algorithm has a high granularity. Checking in a small test yields unpredictable results. I will check in more, unrelated testes until codeclimate is satisified.

**Comment by alecholmez** [comment]
What's the status of this

**Comment by dougfort** [comment]
I have been hoping it would go away. Unless you object, I'm going to heave it.

**Pull request closed without merging**
