### PR TITLE
add cloudwatch to changelog

### LINKED ISSUE #260: 0.1.6 for the cloudobserver additions
tag as 0.1.5 for the cloudobserver additional functionality so that dependent libraries can use it easily.

### PR DESCRIPTION
**Pull request by justincely**
Adding CloudWatch metrics capability to the changelog and tagging 0.1.6 so services that need it can accurately track.  

Closes #260

### CODE REVIEW

**Comment by alecholmez** [comment]
Should I build new binaries?

**Comment by justincely** [comment]
that would be great  - thanks.

**Comment by alecholmez** [comment]
Whoops, can't build binaries here. I thought this was a different repo. Just a library

**Comment by justincely** [comment]
haha, fooled us both.  Wires crossed today

**Pull request merged**
