### PR TITLE
Add a version identifier to the metrics dashboard JSON stream

### LINKED ISSUE #203: Add a version to metrics JSON output
So the Dashboard UI knows what it is getting

### PR DESCRIPTION
**Pull request by dougfort**
closes #203 

output:
```json
$ curl localhost:10001/metrics
{
	"dashboard-metrics-version": "1.0.0",
	"Total/requests": 11,
	"HTTP/requests": 0,
	"HTTPS/requests": 0,
	"RPC/requests": 11,
	"RPC_TLS/requests": 0,
	"all/requests": 11,
	"all/routes": "",
```

Available for dashboard  test:
```bash
#! /bin/bash

set -euxo pipefail

docker run --rm -t -p 10001:10001 -p 20001:20001 -p 30001:30001 drfogout/metricssimple:latest
```

### CODE REVIEW

**Comment by spmcbride1201** [comment]
Please keep this open to give me a chance to discuss this approach with @lucasmoten

**Comment by dougfort** [comment]
This JSON file represents the dashboard metrics. It is different from the statsd metrics and the Prometheus metrics. The format and content of the file are specifically determined by the requirements of the dashboard. 

I'm willing to call it something like ```json-metrics-version``` if that helps.

**Comment by joshua-rutherford** [comment]
Ah, well that gives some insight, but I'm still not sold.  It still inverts the dependency so I'm against it.

**Comment by dougfort** [comment]
How about this:
```json
$ curl localhost:10001/metrics
{
	"grey-matter-metrics-version": "1.0.0",
	"Total/requests": 10,
	"HTTP/requests": 0,
	"HTTPS/requests": 0,
	"RPC/requests": 10,
	"RPC_TLS/requests": 0,
	"function/CatalogStream/requests": 5,
```

**Comment by spmcbride1201** [comment]
This key seems semantically appropriate to me. I'm a bit unclear on the relationship between `gm-fabric-go` and @alecholmez's proxy. Is the proxy built from `gm-fabric-go` or is it entirely different?

**Comment by alecholmez** [comment]
@bushidocodes The proxy uses the SDK and acts as a micro-service sidecar/agent. It is not a replacement for the GM Fabric service-generator

**Pull request merged**
