### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alecholmez**
updated example

### CODE REVIEW

**Comment by alecholmez** [comment]
@justincely I'm not sure. I've never integrated this package so I really have no idea what goes in there. Might be a good idea to reach out to Charles

**Comment by sofiashalotenko** [comment]
@justincely  I actually don't think we need that little "collect your api stats" section at all for our purposes of simply publishing metrics to aws.
@alecholmez Is it definitely Charles that wrote the cloudwatch stuff? I'm only seeing Josh as a contributor to that particular section of gm-fabric-go....but I definitely would like to talk to whoever wrote it.

**Comment by alecholmez** [comment]
@sofiashalotenko It was definitely Charles. We initialized this repo and chopped some commit history. I think we do need that collection of API stats because that callback is what actually sends the metrics snapshot to cloudwatch. I'll have to see after I do some digging but I have a branch: `cloudwatch` that you can poke around in.

**Comment by justincely** [comment]
@alecholmez @sofiashalotenko closing this as superseded.    We're going to be ditching the `cloudwatch` package for the `metrics/cloudobserver` anyway.

**Pull request closed without merging**
