### PR TITLE
WIP: Template Refactoring

### LINKED ISSUE #67: Modify `fabric` generator to  separate templates from code
This is a small, incremental change to move `fabric` toward being a real template engine like [giter8](https://github.com/foundweekends/giter8).

The current generator has templates embedded in `go` code. For example:
```go
package initsvc

var grpcClientTestTemplate = `package main

import (

    "github.com/pkg/errors"
	"github.com/rs/zerolog"

    pb "{{.PBImport}}"
)

func runTest(logger zerolog.Logger, client pb.{{.GoServiceName}}Client) error {
    return errors.New("not implemented")
}

`
```

This task would change `fabric` to read the templates from disk files, with no other change to program logic.

### PR DESCRIPTION
**Pull request by alecholmez**
Just a WIP. I'm opening this so you guys can see what I'm doing. My plan:

- [x] Refactor all templates out of the `initsvc` package and into the `templates` folder for clear separation. 
- [x] Refactor all templates out of the `genproto` package and into the `templates` folder for clear separation.
- [x] Shrink code down by removing unnecessary template files 
- [x] Use Git as a CDN for our templates 
- [x] Create interface `Fetcher` to handle multiple fetch scenarios from GM Data, Git, etc...
- [x] Implement `GitFetcher` which will satisfy the `Fetcher` interface
- [x] Implement `GenericFetcher` which will fetch any file from any source when passed a location
- [ ] Squash bugs

This is just major code cleanup so we can represent in open source 👍 

closes #67

### CODE REVIEW

**Comment by dougfort** [comment]
Also, I'd like to suggest renaming ```Fetcher``` to ```TemplateFetcher```. We may have other fetchers in the future.

**Comment by dougfort** [comment]
FWIW, I hate having ```Err error``` inside ```Source```. We should return  (Source, error)

**Comment by alecholmez** [comment]
Yea I'm thinking the same thing. I thought it would be a good idea and I hate it now

**Comment by dougfort** [comment]
I like the basic plumbing here, but I'd like to argue about the design. 

I would like to see a TemplateFetcher that only takes the name of the template.
```go
type TemplateFetcher interface {
	Fetch(name string) (*template.Template, error)
}
```

Then we would create a fetcher at startup based on the config file: ```template-fetcher = GitFetcher```

The fetcher would contain the location information based on name.

Then we wouldn't have the ```files``` map or functions like:
```
func readServerTemplate(logger zerolog.Logger) (*template.Template, error) {
	return readTemplate(logger, "github.com/deciphernow/gm-fabric-go/cmd/fabric/templates/server.go", "server.go", &git)
}
```

We should just be able to give the name to templ.Merge:
```go
	err = templ.Merge(
		"methods",
		filepath.Join(cfg.MethodsPath(), "new_server.go"),
		struct {
			MethodsPackageName string
			ConfigPackage      string
			ConfigPackageName  string
			PBImport           string
			GoServiceName      string
		}{
			cfg.MethodsPackageName(),
			cfg.ConfigPackageImportPath(),
			cfg.ConfigPackageName(),
			cfg.PBImportPath(),
			cfg.GoServiceName(),
		},
	)
```

And ```templ.Merge``` should call the fetcher to get the right template.

**Comment by joshua-rutherford** [comment]
I admit that I have not fully reviewed this here but I have always preferred determining the method of fetching something by the URL scheme.  It's just concise and clear in most cases.  For example, if I need to get something from a git repository I can `fabric fetch git://github.com/deciphernow/gm-fabric-go` or something to that effect then the scheme tells fabric to use git (which is actually ssh).

I'm open to discussions but I don't see why we have to have a config change to change the source.

**Comment by dougfort** [comment]
I don't want the caller to know the location at all.  The caller (```fabric```) should ask for something like the ```gateway-proxy``` template and not be concerned with where it comes from.

**Comment by alecholmez** [comment]
The template fetcher is still going to need to know where to go look for files. So it will need to know a location. Having that configurable may be a good idea, but my problem is that what happens when we need to fetch templates from different git repos or sources? Do we need to create a different `GitFetcher{}` everytime we use a different location? I went with passing the URL scheme to the fetcher simply because it allows for the greatest flexibility. But I'm definitely open to new options.

**Comment by dougfort** [comment]
The key question is what we really want to use this for. I want to generalize templates in order to clear the decks for a bigger change. I think @joshua-rutherford and maybe @chrismholmes  want to use ```fabric``` as a more generalized templating engine, like giter8. I may be wrong, I only have a vague idea about this.

**Comment by joshua-rutherford** [comment]
@dougfort, I don't want to turn the `fabric` command into a templating engine per se. I just recognize that I do not know what any given user will want their base service to look like.  The point that drove this home to me was when @alecholmez added the docker build script.  That made an assumption about the base image that would be used (it has to).  For many users the first step will be to rip that out and put in a new one.  Why would we not want to provide a path for users to do that from the start?

I don't think there is any need to obfuscate the template source either.  This tool is for Go developers and they more that most know all about pulling stuff from github (or other URLs).  I just think the obfuscation is too restrictive.  As I said though, I'd be okay shipping with a default template location so running `fabric --init SERVICE` without a `--template` parameter would not be an error. Again, that default should be configurable too.

**Pull request closed without merging**
